// flow-typed signature: 22c29eb71f9be7b57d8beb3bb54005c4
// flow-typed version: <<STUB>>/environs_v^0.4.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'environs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'environs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'environs/lib/env' {
  declare module.exports: any;
}

// Filename aliases
declare module 'environs/lib/env.js' {
  declare module.exports: $Exports<'environs/lib/env'>;
}
