// flow-typed signature: 5f6d33eb926344500a03c2ab02475311
// flow-typed version: <<STUB>>/flexboxgrid_v^6.3.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flexboxgrid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'flexboxgrid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flexboxgrid/Gruntfile' {
  declare module.exports: any;
}

declare module 'flexboxgrid/js/index' {
  declare module.exports: any;
}

declare module 'flexboxgrid/src/js/index' {
  declare module.exports: any;
}

declare module 'flexboxgrid/vendor/js/modernizr.flexbox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flexboxgrid/Gruntfile.js' {
  declare module.exports: $Exports<'flexboxgrid/Gruntfile'>;
}
declare module 'flexboxgrid/js/index.js' {
  declare module.exports: $Exports<'flexboxgrid/js/index'>;
}
declare module 'flexboxgrid/src/js/index.js' {
  declare module.exports: $Exports<'flexboxgrid/src/js/index'>;
}
declare module 'flexboxgrid/vendor/js/modernizr.flexbox.js' {
  declare module.exports: $Exports<'flexboxgrid/vendor/js/modernizr.flexbox'>;
}
