// flow-typed signature: 58037f847058fe9c687f97eeb41b5a23
// flow-typed version: <<STUB>>/hpp_v^0.2.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hpp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hpp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hpp/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hpp/lib/index.js' {
  declare module.exports: $Exports<'hpp/lib/index'>;
}
