// flow-typed signature: 651c153a8f5f1622d866fac271fef033
// flow-typed version: <<STUB>>/json-server_v^0.9.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-server/bin/index' {
  declare module.exports: any;
}

declare module 'json-server/lib/cli/bin' {
  declare module.exports: any;
}

declare module 'json-server/lib/cli/index' {
  declare module.exports: any;
}

declare module 'json-server/lib/cli/run' {
  declare module.exports: any;
}

declare module 'json-server/lib/cli/utils/is' {
  declare module.exports: any;
}

declare module 'json-server/lib/cli/utils/load' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/body-parser' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/defaults' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/index' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/mixins' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/rewriter' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/router/index' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/router/nested' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/router/plural' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/router/singular' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/router/validate-data' {
  declare module.exports: any;
}

declare module 'json-server/lib/server/utils' {
  declare module.exports: any;
}

declare module 'json-server/test/cli/fixtures/middlewares/en' {
  declare module.exports: any;
}

declare module 'json-server/test/cli/fixtures/middlewares/jp' {
  declare module.exports: any;
}

declare module 'json-server/test/cli/fixtures/seed' {
  declare module.exports: any;
}

declare module 'json-server/test/cli/index' {
  declare module.exports: any;
}

declare module 'json-server/test/server/mixins' {
  declare module.exports: any;
}

declare module 'json-server/test/server/plural' {
  declare module.exports: any;
}

declare module 'json-server/test/server/singular' {
  declare module.exports: any;
}

declare module 'json-server/test/server/utils' {
  declare module.exports: any;
}

declare module 'json-server/test/server/validate-data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-server/bin/index.js' {
  declare module.exports: $Exports<'json-server/bin/index'>;
}
declare module 'json-server/lib/cli/bin.js' {
  declare module.exports: $Exports<'json-server/lib/cli/bin'>;
}
declare module 'json-server/lib/cli/index.js' {
  declare module.exports: $Exports<'json-server/lib/cli/index'>;
}
declare module 'json-server/lib/cli/run.js' {
  declare module.exports: $Exports<'json-server/lib/cli/run'>;
}
declare module 'json-server/lib/cli/utils/is.js' {
  declare module.exports: $Exports<'json-server/lib/cli/utils/is'>;
}
declare module 'json-server/lib/cli/utils/load.js' {
  declare module.exports: $Exports<'json-server/lib/cli/utils/load'>;
}
declare module 'json-server/lib/server/body-parser.js' {
  declare module.exports: $Exports<'json-server/lib/server/body-parser'>;
}
declare module 'json-server/lib/server/defaults.js' {
  declare module.exports: $Exports<'json-server/lib/server/defaults'>;
}
declare module 'json-server/lib/server/index.js' {
  declare module.exports: $Exports<'json-server/lib/server/index'>;
}
declare module 'json-server/lib/server/mixins.js' {
  declare module.exports: $Exports<'json-server/lib/server/mixins'>;
}
declare module 'json-server/lib/server/rewriter.js' {
  declare module.exports: $Exports<'json-server/lib/server/rewriter'>;
}
declare module 'json-server/lib/server/router/index.js' {
  declare module.exports: $Exports<'json-server/lib/server/router/index'>;
}
declare module 'json-server/lib/server/router/nested.js' {
  declare module.exports: $Exports<'json-server/lib/server/router/nested'>;
}
declare module 'json-server/lib/server/router/plural.js' {
  declare module.exports: $Exports<'json-server/lib/server/router/plural'>;
}
declare module 'json-server/lib/server/router/singular.js' {
  declare module.exports: $Exports<'json-server/lib/server/router/singular'>;
}
declare module 'json-server/lib/server/router/validate-data.js' {
  declare module.exports: $Exports<'json-server/lib/server/router/validate-data'>;
}
declare module 'json-server/lib/server/utils.js' {
  declare module.exports: $Exports<'json-server/lib/server/utils'>;
}
declare module 'json-server/test/cli/fixtures/middlewares/en.js' {
  declare module.exports: $Exports<'json-server/test/cli/fixtures/middlewares/en'>;
}
declare module 'json-server/test/cli/fixtures/middlewares/jp.js' {
  declare module.exports: $Exports<'json-server/test/cli/fixtures/middlewares/jp'>;
}
declare module 'json-server/test/cli/fixtures/seed.js' {
  declare module.exports: $Exports<'json-server/test/cli/fixtures/seed'>;
}
declare module 'json-server/test/cli/index.js' {
  declare module.exports: $Exports<'json-server/test/cli/index'>;
}
declare module 'json-server/test/server/mixins.js' {
  declare module.exports: $Exports<'json-server/test/server/mixins'>;
}
declare module 'json-server/test/server/plural.js' {
  declare module.exports: $Exports<'json-server/test/server/plural'>;
}
declare module 'json-server/test/server/singular.js' {
  declare module.exports: $Exports<'json-server/test/server/singular'>;
}
declare module 'json-server/test/server/utils.js' {
  declare module.exports: $Exports<'json-server/test/server/utils'>;
}
declare module 'json-server/test/server/validate-data.js' {
  declare module.exports: $Exports<'json-server/test/server/validate-data'>;
}
