// flow-typed signature: 918de625271fd6e8f9b2f5a2d97b00c7
// flow-typed version: <<STUB>>/loaders.css_v^0.1.2/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loaders.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'loaders.css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loaders.css/loaders.css' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loaders.css/loaders.css.js' {
  declare module.exports: $Exports<'loaders.css/loaders.css'>;
}
