// flow-typed signature: 4b6c3865162426771518def49011d41f
// flow-typed version: <<STUB>>/react-loaders_v^2.3.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loaders'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loaders' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loaders/dist/react-loaders' {
  declare module.exports: any;
}

declare module 'react-loaders/gulpfile' {
  declare module.exports: any;
}

declare module 'react-loaders/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loaders/dist/react-loaders.js' {
  declare module.exports: $Exports<'react-loaders/dist/react-loaders'>;
}
declare module 'react-loaders/gulpfile.js' {
  declare module.exports: $Exports<'react-loaders/gulpfile'>;
}
declare module 'react-loaders/webpack.config.js' {
  declare module.exports: $Exports<'react-loaders/webpack.config'>;
}
